const mutations = {
  IS_LOGGED_IN: 'IS_LOGGED_IN',
  LOGIN_LOADER: 'LOGIN_LOADER',
  IS_REGISTERED: 'IS_REGISTERED',
  SIGNUP_LOADER: 'SIGNUP_LOADER',
  IS_PASSWORD_RESET: 'IS_PASSWORD_RESET',
  RESET_LOADER: 'RESET_LOADER',
  SHOW_NOTIFY: 'SHOW_NOTIFY',
  USER: 'USER',
};

export default mutations;
